"""Feature registry loading, selection validation, and CMake rendering."""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path

import yaml

from .models import (
    CMakeValue,
    FeatureMode,
    FeatureRegistry,
    FeatureSelection,
)
from .resources import registry_path, resolver_path


def load_registry(path: Path | None = None) -> FeatureRegistry:
    """Load and validate the packaged registry or an explicit test registry."""
    source = path or registry_path()
    raw = yaml.safe_load(source.read_text())
    if not isinstance(raw, dict):
        raise ValueError(f"registry must be a mapping: {source}")
    raw_features = raw.get("features")
    if not isinstance(raw_features, dict):
        raise ValueError(f"registry features must be a mapping: {source}")
    normalized = {
        **raw,
        "features": {
            name: {**value, "name": name} if isinstance(value, dict) else value
            for name, value in raw_features.items()
        },
    }
    registry = FeatureRegistry.model_validate(normalized)
    module_root = None if path is None else source.parent / "cmake" / "resolvers"
    for feature in registry.features.values():
        module = (
            resolver_path(feature.name)
            if module_root is None
            else module_root / f"{feature.name}.cmake"
        ).resolve()
        if not module.is_file():
            raise ValueError(f"{feature.name}: missing resolver module: {module}")
    return registry


def resolution_order(registry: FeatureRegistry) -> tuple[str, ...]:
    """Return a stable dependency-first feature order."""
    ordered: list[str] = []
    visited: set[str] = set()

    def visit(name: str) -> None:
        if name in visited:
            return
        for dependency in registry.features[name].dependencies:
            visit(dependency)
        visited.add(name)
        ordered.append(name)

    for name in registry.features:
        visit(name)
    return tuple(ordered)


def _cmake_quote(value: CMakeValue) -> str:
    text = (
        ";".join(str(item) for item in value)
        if isinstance(value, tuple)
        else str(value)
    )
    return text.replace("\\", "\\\\").replace('"', '\\"')


def render_manifest(
    registry: FeatureRegistry,
    providers: Mapping[str, FeatureMode],
    option_values: Mapping[str, str],
) -> str:
    """Render deterministic input for the post-project CMake resolver."""
    selection = FeatureSelection.model_validate(dict(providers))
    selection.validate_for(registry)
    expected_options = {
        name for feature in registry.features.values() for name in feature.options
    }
    if option_values.keys() != expected_options:
        missing = expected_options - option_values.keys()
        unknown = option_values.keys() - expected_options
        msg = (
            "option keys do not match registry; "
            f"missing={sorted(missing)}, unknown={sorted(unknown)}"
        )
        raise ValueError(msg)

    ordered = resolution_order(registry)
    lines = [
        "# Generated by tula_cmake. Do not edit.",
        f'set(TULA_FEATURES "{";".join(ordered)}")',
    ]
    for name in ordered:
        feature = registry.features[name]
        module = resolver_path(name).resolve()
        lines.extend(
            [
                f'set(TULA_FEATURE_{name}_MODE "{selection.root[name].value}")',
                (f'set(TULA_FEATURE_{name}_MODULE "{_cmake_quote(str(module))}")'),
            ]
        )
        for key, value in feature.cmake_vars.items():
            lines.append(f'set(TULA_FEATURE_{name}_{key} "{_cmake_quote(value)}")')
        for option_name, option in feature.options.items():
            value = option_values[option_name]
            if value not in option.values:
                raise ValueError(f"{option_name}: unsupported value {value!r}")
            lines.append(f'set({option.cmake_variable} "{_cmake_quote(value)}")')
    lines.append("")
    return "\n".join(lines)
