packages:
  cmake:
    externals:
      - spec: cmake@3.28.3
        prefix: /usr
    buildable: false
  cxx:
    require: gcc@14.2.0
  fmt:
    externals:
      - spec: fmt@9.1.0
        prefix: /usr
    buildable: false
  gcc:
    externals:
      - spec: gcc@14.2.0 languages:='c,c++'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc-14
            cxx: /usr/bin/g++-14
  gmake:
    externals:
      - spec: gmake@4.3
        prefix: /usr
    buildable: false
  llvm:
    externals:
      - spec: llvm@20.1.2+clang~flang~lld~lldb
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/clang-20
            cxx: /usr/bin/clang++-20
  spdlog:
    externals:
      - spec: spdlog@1.12.0
        prefix: /usr
    buildable: false
