include_guard(GLOBAL)

function(tula_add_config_header)
    cmake_parse_arguments(ARG "" "TARGET;ALIAS;PREFIX;OUTPUT" "" ${ARGN})
    foreach(_required TARGET PREFIX OUTPUT)
        if(NOT ARG_${_required})
            message(FATAL_ERROR "tula_add_config_header requires ${_required}")
        endif()
    endforeach()
    if(NOT ARG_PREFIX MATCHES "^[A-Z][A-Z0-9_]*$")
        message(FATAL_ERROR "Config-header PREFIX must be an uppercase C identifier")
    endif()
    if(TARGET "${ARG_TARGET}")
        message(FATAL_ERROR "Config-header target already exists: ${ARG_TARGET}")
    endif()

    if(PROJECT_VERSION)
        set(_project_version "${PROJECT_VERSION}")
    else()
        set(_project_version "0.0.0")
    endif()

    set(TULA_CONFIG_PREFIX "${ARG_PREFIX}")
    set(TULA_CONFIG_VERSION "${_project_version}")
    set(TULA_CONFIG_FEATURE_DEFINITIONS "")
    get_property(_features GLOBAL PROPERTY TULA_FEATURE_NAMES)
    foreach(_feature IN LISTS _features)
        string(TOUPPER "${_feature}" _feature_upper)
        tula_get_feature_provider(_provider "${_feature}")
        if(TARGET "tula::${_feature}")
            set(_enabled 1)
        else()
            set(_enabled 0)
        endif()
        string(APPEND TULA_CONFIG_FEATURE_DEFINITIONS
            "#define ${ARG_PREFIX}_HAS_${_feature_upper} ${_enabled}\n"
            "#define ${ARG_PREFIX}_${_feature_upper}_PROVIDER \"${_provider}\"\n")
    endforeach()
    set(_include_root "${CMAKE_CURRENT_BINARY_DIR}/generated")
    set(_output "${_include_root}/${ARG_OUTPUT}")
    get_filename_component(_output_dir "${_output}" DIRECTORY)
    file(MAKE_DIRECTORY "${_output_dir}")
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/TulaConfig.h.in" "${_output}" @ONLY)

    add_library("${ARG_TARGET}" INTERFACE)
    target_include_directories(
        "${ARG_TARGET}"
        INTERFACE "$<BUILD_INTERFACE:${_include_root}>"
    )
    if(ARG_ALIAS)
        add_library("${ARG_ALIAS}" ALIAS "${ARG_TARGET}")
    endif()
endfunction()
