# _deps_callbacks.cmake - Helper functions for dependency target files
#
# Reduces boilerplate in TULA_{PACKAGE}_TRY_* and TULA_{PACKAGE}_CREATE_WRAPPER functions

include_guard(GLOBAL)

#[=======================================================================[
@brief Helper to set success variable and return early if target exists
@param PACKAGE Package name (e.g., Eigen3)
@param UPSTREAM_TARGET Upstream target name (e.g., Eigen3::Eigen)
@param MODE Mode name (CONAN, CPM, SYSTEM)
]=======================================================================]
function(_tula_check_target_exists PACKAGE UPSTREAM_TARGET MODE)
    if(TARGET ${UPSTREAM_TARGET})
        set(TULA_${PACKAGE}_${MODE}_SUCCESS TRUE PARENT_SCOPE)
        set(_TULA_TARGET_EXISTS TRUE PARENT_SCOPE)
    else()
        set(_TULA_TARGET_EXISTS FALSE PARENT_SCOPE)
    endif()
endfunction()

#[=======================================================================[
@brief Standard TRY_CONAN implementation for header-only libraries
@param PACKAGE Package name (e.g., Eigen3)
@param UPSTREAM_TARGET Upstream target name (e.g., Eigen3::Eigen)

Uses find_package() to locate the CMake config files generated by CMakeDeps.
Conan's CMakeDeps generator creates the target automatically, so we just verify it exists.
]=======================================================================]
function(tula_try_conan_header_only PACKAGE UPSTREAM_TARGET)
    _tula_check_target_exists(${PACKAGE} ${UPSTREAM_TARGET} CONAN)
    if(_TULA_TARGET_EXISTS)
        return()
    endif()
    
    # Try to find the package via generated CMake config files from CMakeDeps
    # Conan's CMakeDeps creates <Package>Config.cmake files that define targets
    find_package(${PACKAGE} CONFIG QUIET)
    
    if(TARGET ${UPSTREAM_TARGET})
        message(STATUS "    Found ${PACKAGE} via Conan CMakeDeps")
        set(TULA_${PACKAGE}_CONAN_SUCCESS TRUE PARENT_SCOPE)
    else()
        message(STATUS "    ${PACKAGE} not found via Conan CMakeDeps")
        set(TULA_${PACKAGE}_CONAN_SUCCESS FALSE PARENT_SCOPE)
    endif()
endfunction()

#[=======================================================================[
@brief Standard TRY_CPM implementation
@param PACKAGE Package name (e.g., Eigen3)
@param UPSTREAM_TARGET Upstream target name (e.g., Eigen3::Eigen)
@param ... Additional arguments passed to CPMAddPackage

Usage:
    tula_try_cpm(Eigen3 Eigen3::Eigen
        NAME Eigen3
        URL "https://gitlab.com/libeigen/eigen/-/archive/3.4.1/eigen-3.4.1.tar.gz"
        OPTIONS "EIGEN_BUILD_DOC OFF" "BUILD_TESTING OFF"
    )
]=======================================================================]
function(tula_try_cpm PACKAGE UPSTREAM_TARGET)
    _tula_check_target_exists(${PACKAGE} ${UPSTREAM_TARGET} CPM)
    if(_TULA_TARGET_EXISTS)
        return()
    endif()
    
    include(_ensure_cpm)
    
    # Forward remaining arguments to CPMAddPackage
    CPMAddPackage(${ARGN})
    
    if(${PACKAGE}_ADDED OR TARGET ${UPSTREAM_TARGET})
        message(STATUS "    Fetched ${PACKAGE} via CPM")
        set(TULA_${PACKAGE}_CPM_SUCCESS TRUE PARENT_SCOPE)
    else()
        message(STATUS "    CPM fetch failed for ${PACKAGE}")
        set(TULA_${PACKAGE}_CPM_SUCCESS FALSE PARENT_SCOPE)
    endif()
endfunction()

#[=======================================================================[
@brief Standard TRY_SYSTEM implementation
@param PACKAGE Package name (e.g., Eigen3)
@param UPSTREAM_TARGET Upstream target name (e.g., Eigen3::Eigen)
@param FIND_PACKAGE_NAME Optional find_package name (defaults to PACKAGE)
]=======================================================================]
function(tula_try_system PACKAGE UPSTREAM_TARGET)
    set(_optional_args ${ARGN})
    list(LENGTH _optional_args _num_args)
    
    if(_num_args GREATER 0)
        list(GET _optional_args 0 _find_name)
    else()
        set(_find_name ${PACKAGE})
    endif()
    
    _tula_check_target_exists(${PACKAGE} ${UPSTREAM_TARGET} SYSTEM)
    if(_TULA_TARGET_EXISTS)
        return()
    endif()
    
    find_package(${_find_name} CONFIG QUIET)
    
    if(TARGET ${UPSTREAM_TARGET})
        message(STATUS "    Found ${PACKAGE} via system find_package")
        set(TULA_${PACKAGE}_SYSTEM_SUCCESS TRUE PARENT_SCOPE)
    else()
        message(STATUS "    System find_package failed for ${PACKAGE}")
        set(TULA_${PACKAGE}_SYSTEM_SUCCESS FALSE PARENT_SCOPE)
    endif()
endfunction()

#[=======================================================================[
@brief Standard CREATE_WRAPPER implementation for simple cases
@param PACKAGE Package name (e.g., Eigen3)
@param UPSTREAM_TARGET Upstream target to wrap (e.g., Eigen3::Eigen)
@param ... Additional dependencies to link

Usage:
    tula_create_wrapper(Eigen3 Eigen3::Eigen tula::perflibs)
]=======================================================================]
function(tula_create_wrapper PACKAGE UPSTREAM_TARGET)
    set(_tula_target "tula_${PACKAGE}")
    
    if(TARGET ${_tula_target})
        return()  # Already created
    endif()
    
    if(NOT TARGET ${UPSTREAM_TARGET})
        message(FATAL_ERROR "Cannot create wrapper: ${UPSTREAM_TARGET} target does not exist")
    endif()
    
    include(make_tula_target)
    make_tula_target(${PACKAGE} ${UPSTREAM_TARGET} ${ARGN})
endfunction()
