include_guard(GLOBAL)

include(TulaConfigHeader)

function(tula_resolve_features)
    get_property(_resolved GLOBAL PROPERTY TULA_FEATURES_RESOLVED)
    if(_resolved)
        return()
    endif()
    if(NOT PROJECT_NAME)
        message(FATAL_ERROR "tula_resolve_features() must be called after project()")
    endif()
    if(NOT TULA_FEATURE_MANIFEST OR NOT EXISTS "${TULA_FEATURE_MANIFEST}")
        message(FATAL_ERROR
            "TULA_FEATURE_MANIFEST is unavailable; run 'conan install' and use its preset")
    endif()

    include("${TULA_FEATURE_MANIFEST}")
    foreach(_feature IN LISTS TULA_FEATURES)
        set(_mode_variable "TULA_FEATURE_${_feature}_MODE")
        set(_mode "${${_mode_variable}}")
        if(_mode STREQUAL "disabled")
            message(STATUS "(tula) ${_feature}: disabled")
            set_property(GLOBAL PROPERTY "TULA_FEATURE_${_feature}_PROVIDER" "disabled")
            continue()
        endif()

        set(_module_variable "TULA_FEATURE_${_feature}_MODULE")
        include("${${_module_variable}}")
        set(_resolver "tula_resolve_${_feature}")
        if(NOT COMMAND "${_resolver}")
            message(FATAL_ERROR "${_feature}: missing resolver ${_resolver}()")
        endif()
        cmake_language(CALL "${_resolver}" "${_mode}")
        if(NOT TARGET "tula::${_feature}")
            message(FATAL_ERROR
                "${_feature}: ${_mode} provider did not create tula::${_feature}")
        endif()
        set_property(GLOBAL PROPERTY "TULA_FEATURE_${_feature}_PROVIDER" "${_mode}")
        message(STATUS "(tula) ${_feature}: ${_mode}")
    endforeach()
    set_property(GLOBAL PROPERTY TULA_FEATURES_RESOLVED TRUE)
endfunction()

function(tula_get_feature_provider OUT_VAR FEATURE)
    get_property(_provider GLOBAL PROPERTY "TULA_FEATURE_${FEATURE}_PROVIDER")
    if(NOT _provider)
        set(_provider "disabled")
    endif()
    set("${OUT_VAR}" "${_provider}" PARENT_SCOPE)
endfunction()
